import { describe, expect, it } from 'vitest';
import { getSecretFromSharesStr, makeSharesStr, mod, modInv } from '../util';

describe('mod', () => {
    it('returns a mod b', () => {
        expect(mod(2, 3)).toBe(2);
        expect(mod(3, 2)).toBe(1);
        expect(mod(13, 11)).toBe(2);
    });
});

describe('modInv', () => {
    it('returns a modInv b', () => {
        expect(modInv(3, 7)).toBe(5);
        expect(modInv(7, 3)).toBe(1);
        expect(modInv(5431, 1231)).toBe(624);
        expect(() => modInv(5432, 1234)).toThrowError(
            new Error('5432 does not have modInv 1234'),
        );
    });
});

describe('getSecretFromSharesStr - integration', () => {
    it('getSecretFromSharesStr decodes shares', () => {
        const share1 =
            '1:6bj:65q:e7:5ww:5u3:5tn:5yw:43:3j:66w:69n:6as:5wc:67v:88:5ye:9f:62r:5uw:k:5z3:m9:b4:25:32:5or';
        const share2 =
            '2:6bj:5gf:kt:4vt:4nz:4po:57d:nq:bq:636:o:9z:4yx:5tm:7o:5ic:7i:5a1:4x6:5sm:53a:1kn:18o:4f:rg:4ds';
        const share3 =
            '3:6bj:4ai:mn:3ba:2w7:32p:41u:1q5:rh:636:au:yz:3jk:565:6b9:50s:678:3y9:3le:4rx:3r7:2yh:2tk:7r:22y:2fl';
        const expectedResult = `hello there
1234 meow !@#`;
        expect(getSecretFromSharesStr([share1, share2, share3])).toBe(
            expectedResult,
        );
        expect(getSecretFromSharesStr([share3, share1, share2])).toBe(
            expectedResult,
        );
    });

    it('getSecretFromSharesStr decodes shares generated by the makeSharesStr fn if prime is sufficiently large', () => {
        const prime = 2 ** 13 - 1;
        const secret = `testttt 1234
        nfsdjnfskd
        asfas`;
        const shares = makeSharesStr(secret, 4, prime);
        expect(shares.length).toBe(4);
        expect(getSecretFromSharesStr(shares)).toBe(secret);
    });
});
